with open('src/api/client.js', 'a', encoding='utf-8') as f:
    f.write("""
export const evolveHero = (heroId, targetClass) => request('/heroes/' + heroId + '/evolve', { method: 'POST', body: JSON.stringify({ target_class: targetClass }) })
export const listEquipment = () => request('/equipment/')
export const craftEquipment = (crafterId) => request('/equipment/craft', { method: 'POST', body: JSON.stringify({ crafter_id: crafterId }) })
export const equipItem = (equipmentId, heroId) => request('/equipment/equip', { method: 'POST', body: JSON.stringify({ equipment_id: equipmentId, hero_id: heroId }) })
export const unequipItem = (equipmentId) => request('/equipment/unequip', { method: 'POST', body: JSON.stringify({ equipment_id: equipmentId }) })
export const getFacilities = () => request('/base/facilities')
export const buildFacility = (type) => request('/base/facilities/build', { method: 'POST', body: JSON.stringify({ facility_type: type }) })
export const assignFacility = (facId, heroId) => request('/base/facilities/assign', { method: 'POST', body: JSON.stringify({ facility_id: facId, hero_id: heroId }) })
export const removeFacility = (heroId) => request('/base/facilities/remove', { method: 'POST', body: JSON.stringify({ hero_id: heroId }) })
export const trainSkill = (heroId, skillId, sparringPartnerId = null) => request('/base/facilities/training-grounds/train', { method: 'POST', body: JSON.stringify({ hero_id: heroId, skill_id: skillId, sparring_partner_id: sparringPartnerId }) })
export const mageTowerResearch = () => request('/base/facilities/mage-tower/research', { method: 'POST' })
export const cleanupPortraits = () => request('/portrait-cache/cleanup', { method: 'POST' })
export const regeneratePortraits = () => request('/portrait-cache/regenerate', { method: 'POST' })
export const getCacheStatus = () => request('/portrait-cache/status')
export const promoteHero = (heroId) => request(`/heroes/${heroId}/promote`, { method: 'POST' })
export const regenerateProfile = (heroId) => request(`/heroes/${heroId}/regenerate-profile`, { method: 'POST' })
export const getLegacies = () => request('/heroes/legacies')
export const getBonds = () => request('/heroes/bonds')
export const getPityInfo = () => request('/gacha/pity-info')
export const redeemSpark = () => request('/gacha/spark-redeem', { method: 'POST' })
""")
